[package]
name = "libthermite"
version = "0.4.0-alpha"
edition = "2021"
description = "Crate for managing Northstar mods"
license = "MIT"
repository = "https://gitea.greenboi.me/Emerald/thermite"
exclude = ["commands/"]

[lib]
name = "thermite"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3.25"
indicatif = "0.17.1"
log = "0.4.17"
reqwest = { version = "0.11.12", features = ["stream"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
thiserror = "1.0.37"
zip = "0.6.3"

[dev-dependencies]
tokio-test = "0.4.2"
