[package]
name = "libthermite"
version = "0.6.5" # managed by release.sh
edition = "2021"
description = "Crate for managing Northstar mods"
license = "MIT"
repository = "https://forge.greenboi.me/Emerald/thermite"
exclude = ["commands/", "*.zip"]

[workspace]
members = ["xtask"]

[lib]
name = "thermite"

[[example]]
name = "steam"
required-features = ["steam"]

[dependencies]
flate2 = { version = "1.0.25", optional = true }
json5 = "0.4.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
steamlocate = { version = "1.1.1", optional = true }
tar = { version = "0.4.38", optional = true }
thiserror = "1.0.38"
tracing = "0.1.37"
ureq = "2.6.2"
zip = "0.6.3"

[features]
default = []
steam = ["steamlocate"]
proton = ["tar", "flate2"]

[dev-dependencies]
indicatif = "0.17.3"
mockall = { version = "0.11.4" }
