[package]
name = "libthermite"
version = "0.4.0"
edition = "2021"
description = "Crate for managing Northstar mods"
license = "MIT"
repository = "https://forge.greenboi.me/Emerald/thermite"
exclude = ["commands/"]

[lib]
name = "thermite"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3.25"
indicatif = "0.17.2"
log = "0.4.17"
reqwest = { version = "0.11.13", features = ["stream"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
thiserror = "1.0.38"
zip = "0.6.3"

[dev-dependencies]
tokio = { version = "1.24.1", features = ["full"] }
tokio-test = "0.4.2"
